### PR TITLE
with reference

### PR DESCRIPTION
**Pull request by ArnoldLIULJ**
Fred, would you mind integrating it into intro, after YIFENG updates his change.

### CODE REVIEW

**Comment by FredChenEcon** [comment]
Sure

**Comment by FredChenEcon** [comment]
@ArnoldLIULJ please see changes I made in commit.

1) move citations into references.bib file. [](https://scholar.google.co.uk/) will help you automatically form the citation code

2) Please put each sentence on a new line, makes reading the tex file easier.

**Comment by karolina-sowinska** [comment]
I changed a few bits:
-introduction
-some wording
-added a point about the key advantage of the model

**Comment by karolina-sowinska** [comment]
I rewrote the whole paragraph to abstract away from one paper and generalise about the content-based recommendation system.

Can someone please help me fix the citation though? VSCode suddenly started complaining about them (overleaf version works fine).

**Pull request merged**
