### PR TITLE
Requirements

### PR DESCRIPTION
**Pull request by ArnoldLIULJ**
Somehow once I put the Gantt chart inside the section, the font of texts after it changed.
so I remove the chart to the Appendices, does it make sense?
If anyone can help solve this problem.

### CODE REVIEW

**Comment by FredChenEcon** [comment]
Probably to do with the `\sffamily` command

**Comment by FredChenEcon** [comment]
@karolina-sowinska doesn't compile?

**Comment by karolina-sowinska** [comment]
> @karolina-sowinska to answer your questions, i think a table would be more clear. Like in https://www.imperial.ac.uk/media/imperial-college/faculty-of-engineering/computing/public/1718-pg-projects/Group2-Machine-Learning-for-Product-Recognition.pdf
> 
> Then you can label the priorities clearly as well.
> 
> @ArnoldLIULJ I think better to have a png of the gantt chart and put it in the main text, rather than the appendix. Also if you can change the weeks to actual dates that would be good
> 
> Thanks guys

I've made all the changes that you requested, except for changing weeks to actual dates in the Gantt. 

Also, please review if estimated completions dates in the goals table make sense - I put some very arbitrary stuff there. If OK, please accept the pull request!

**Comment by karolina-sowinska** [comment]
> @karolina-sowinska doesn't compile?

Hm... compiled on my end, altough with some difficulty (switching off/on VSCode, but that really is the standard for working with LaTeX in VSCode for me..)

**Comment by karolina-sowinska** [comment]
image

The table should not be causing the trouble, because it compiled well when seperated.

**Comment by ArnoldLIULJ** [comment]
I tried to change the weeks to be the exact date in Gantt chart. 
But it will make it too crowded, because it is too many. Also, by default it is week not date, which makes it harder to adjust its composing.

**Comment by ArnoldLIULJ** [comment]
Yes. I will make it png to include instead of putting it at the Appendix. soon be done

**Comment by karolina-sowinska** [comment]
@ArnoldLIULJ  does it compile on your end after my commit?

**Comment by karolina-sowinska** [comment]
Because it does work for me, so I don't know what to fix. 

image

image

**Comment by ArnoldLIULJ** [comment]
> @ArnoldLIULJ does it compile on your end after my commit?

it does not compile.
I will see if I can make it by somehow importing or editing.
can be due to the operating system difference

**Comment by FredChenEcon** [comment]
@karolina-sowinska problem is coming from your table. In the new commit is a snippet from mine which compiles, can you reformat it to contain your original text please.

@ArnoldLIULJ ok, can you add some description to the gantt chart please, regarding what those goals are and why we estimate they will take that long

**Comment by ArnoldLIULJ** [comment]
> @karolina-sowinska problem is coming from your table. In the new commit is a table snippet from mine which compiles, can you reformat it to contain your original text please.
> 
> @ArnoldLIULJ @karolina-sowinska ok, can you guys add some description to the gantt chart please, regarding what those goals are and why we estimate they will take that long

@karolina-sowinska  leave it to me because I already make it compile on my own. no need to reformat from Fred one

**Comment by ArnoldLIULJ** [comment]
@FredChenEcon I update the file, see if it compile on your own laptop

**Comment by karolina-sowinska** [comment]
Thanks @Arnold!

**Comment by FredChenEcon** [comment]
Please add the description for the gantt chart, thank you

**Comment by ArnoldLIULJ** [comment]
> @ArnoldLIULJ please do avoid force pushing - you keep overwriting my edits
> 
> Can you rebase your description off [be4c0fb](https://github.com/ProjectKiev/ReportOne/commit/be4c0fb13b0726abd559971cf0c366ec409a15cd) please thanks

As I said, the [be4c0fb] is not necessary for me because I can fix the compilation error without your new table snippet. So I just force push it, because if I pull request(rebase on your one), I will need to delete your parts as well.

As I can see, there is nearly no point of rebasing that one. If any, let me know

**Pull request merged**
